services:
  dev:
    build:
      context: .
      args:
        - ROS_DISTRO=${ROS_DISTRO}
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      CYCLONEDDS_URI: "file://${CYCLONEDDS_URI_FILE}"
      FOXGLOVE_PORT: ${FOXGLOVE_PORT}
    ports:
      - "${FOXGLOVE_PORT}:${FOXGLOVE_PORT}"
      - "${HOST_IP}:${UDP_PORT_RANGE}:${UDP_PORT_RANGE}/udp"
    volumes:
      - ${USER_PROVIDED_DIR}:/ros2
      - ./cyclonedds.xml:/cyclonedds.xml:ro
    privileged: true
    stdin_open: true
    tty: true
